version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
    groups:
      npm-production:
        dependency-type: production
  - package-ecosystem: npm
    directory: /apps/web
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /services/payments-go
    schedule: { interval: weekly }
  - package-ecosystem: maven
    directory: /services/inventory-java
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: terraform
    directory: /platform/terraform/environments/dev
    schedule: { interval: weekly }
