{{- range $name, $config := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "northstar.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/name: {{ $name }}, app.kubernetes.io/instance: {{ $.Release.Name }} }
  ports: [{ name: http, port: {{ $config.port }}, targetPort: http, protocol: TCP }]
{{- end }}
