name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: npm }
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
      - run: npm test

  platform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v4
        with: { terraform_version: "1.15.6", terraform_wrapper: false }
      - uses: azure/setup-helm@v4
        with: { version: "4.2.2" }
      - run: terraform fmt -check -recursive platform/terraform
      - run: helm lint platform/helm/northstar --set global.imageDigest=sha256:0000000000000000000000000000000000000000000000000000000000000000
      - run: helm template northstar platform/helm/northstar --namespace northstar --set global.imageDigest=sha256:0000000000000000000000000000000000000000000000000000000000000000 >/dev/null

  filesystem-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,misconfig,secret
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
